[theme]
# This is your "green theme"
primaryColor="#4CAF50"

# This sets the default to "dark mode"
base="dark"

# Other dark theme colors
backgroundColor="#0E1117"
secondaryBackgroundColor="#1c1f2b"
textColor="#FAFAFA"
font="sans serif"